export const CONFIG_ENV = {
  dbUrl: 'DATABASE_URL',
  port: 'PORT',
  jwtAccessSecret: 'JWT_ACCESS_SECRET',
  jwtAccessExpiresIn: 'JWT_ACCESS_EXPIRES_IN',
  jwtRefreshSecret: 'JWT_REFRESH_SECRET',
  jwtRefreshExpiresIn: 'JWT_REFRESH_EXPIRES_IN',
  resendApiKey: 'RESEND_API_KEY',
  resendFromEmail: 'RESEND_FROM_EMAIL',
  supabaseUrl: 'SUPABASE_URL',
  supabasePublishableKey: 'SUPABASE_PUBLISHABLE_KEY',
  supabaseSecretKey: 'SUPABASE_SECRET_KEY',
  supabaseJwksUrl: 'SUPABASE_JWKS_URL',
  supabaseManifestBucket: 'SUPABASE_MANIFEST_BUCKET',
};