import { ApiProperty } from '@nestjs/swagger';
import { Role } from '../../../prisma/prisma-client';

export class AdminOverviewRevenueModel {
  @ApiProperty({ example: 5150000, description: 'Total whole app revenue in VND' })
  totalRevenueVnd: number;

  @ApiProperty({ example: 202.77, description: 'USD equivalent calculated via live rate' })
  usdEquivalent: number;

  @ApiProperty({ example: 1450.7, description: 'CNY equivalent calculated via live rate' })
  cnyEquivalent: number;
}

export class TopSellerProductModel {
  @ApiProperty({ example: 1, description: 'Rank (#1, #2, #3)' })
  rank: number;

  @ApiProperty({ example: '9c1f...uuid' })
  id: string;

  @ApiProperty({ example: 570 })
  appId: number;

  @ApiProperty({ example: 'Elden Ring: Shadow of the Erdtree' })
  name: string;

  @ApiProperty({ example: 'Souls-like RPG' })
  category: string;

  @ApiProperty({ example: 990000, description: 'Product price in VND' })
  priceVnd: number;

  @ApiProperty({ nullable: true, example: 'https://cdn.example.com/eldenring.jpg' })
  imageUrl: string | null;

  @ApiProperty({ example: 415, description: 'Number of paid users for this game' })
  paidUsersCount: number;

  @ApiProperty({ example: 410850000, description: 'Total revenue generated by this game in VND' })
  totalRevenueVnd: number;
}

export class AccountMetricsModel {
  @ApiProperty({ example: 5, description: 'Count of active accounts' })
  activeAccountsCount: number;

  @ApiProperty({ example: 1, description: 'Count of banned accounts' })
  bannedAccountsCount: number;
}

export class RecentUserModel {
  @ApiProperty({ example: '9c1f...uuid' })
  id: string;

  @ApiProperty({ example: 'Kenji Sato' })
  username: string;

  @ApiProperty({ example: 'kenji.sato@tokyo-esports.jp' })
  email: string;

  @ApiProperty({ enum: Role, example: Role.CUSTOMER })
  role: Role;

  @ApiProperty({ example: 'active', description: 'Account status: active or banned' })
  status: 'active' | 'banned';

  @ApiProperty()
  createdAt: Date;
}

export class AdminOverviewResponseModel {
  @ApiProperty({ example: 'weekly' })
  period: string;

  @ApiProperty({ example: 'Last 7 Days' })
  dateRangeText: string;

  @ApiProperty({ type: AdminOverviewRevenueModel })
  revenue: AdminOverviewRevenueModel;

  @ApiProperty({ type: [TopSellerProductModel] })
  topSellers: TopSellerProductModel[];

  @ApiProperty({ type: AccountMetricsModel })
  accountMetrics: AccountMetricsModel;

  @ApiProperty({ type: [RecentUserModel] })
  recentUsers: RecentUserModel[];
}
